name: Pipeline de CI/CD - Meu Primeiro Robô

# Força o GitHub a usar o Node 24 para rodar as ações
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# Quando este workflow deve ser executado?
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Definindo os trabalhos (jobs) que serão executados
jobs:
  verificacoes-basicas:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixando o código do repositório
        uses: actions/checkout@v4

      - name: 2. Verificar estrutura do projeto
        run: ls -R

      - name: 3. Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 4. Executando a aplicação
        run: node app.js

      - name: 5. Mensagem de sucesso
        run: echo "O robô terminou as verificações com sucesso!"
             echo "Parabéns! Seu primeiro pipeline de CI está funcionando!"
